from conan import ConanFile
from conan.tools.build import can_run, check_min_cppstd
from conan.tools.cmake import CMake, cmake_layout
from conan.tools.files import copy, update_conandata
from conan.tools.scm import Git

import os


class MathConan(ConanFile):
    """ Conan recipe for Math """
    """ Currently the library is header only, but there are compiled tests """
    """ so we keep the usual settings """

    name = "math"
    license = "MIT"
    url = "https://github.com/Adnn/math"
    description = "A mathematic library implementation, first concentrating on linear algrebra."
    topics = ("math", "linear algebra", "geometry", "graphics",)

    settings = ("os", "compiler", "build_type", "arch")
    options = {}
    default_options = {}

    generators = "CMakeDeps", "CMakeToolchain"
    revision_mode = "scm"


    def validate(self):
        if self.settings.compiler.get_safe("cppstd"):
            check_min_cppstd(self, "20")


    # Handled at the profile level for the moment
    #def tool_requires(self):
    #    self.tool_requires("cmake/[>=3.31]")


    def layout(self):
        # The root of the project is one level above
        self.folders.root = ".."
        cmake_layout(self)


    def export(self):
        git = Git(self, self.recipe_folder)
        # Save the url and commit in conandata.yml
        # Unsafe atm since it is missing the repository argument,
        # so we save the coordinates manually
        #git.coordinates_to_conandata()
        url, commit = git.get_url_and_commit(repository=True)
        update_conandata(self, {"scm": {"url": url, "commit": commit}})


    def source(self):
        # we recover the saved url and commit from conandata.yml and use them to get sources
        git = Git(self)
        git.checkout_from_conandata_coordinates()
        git.run("submodule update --init")


    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        if can_run(self):
            cmake.test()


    def package(self):
        cmake = CMake(self)
        cmake.install()
        copy(self, "LICENSE", src=self.source_folder, dst=os.path.join(self.package_folder, "licenses"))


    def package_info(self):
        # Let's bite the bullet and repeate ourselve with a complete cpp_info,
        # waiting for sufficent Common Package Specification support in Conan an CMake.
        ## Disable the config package that would otherwise be generated by CMakeDeps
        #self.cpp_info.set_property("cmake_find_mode", "none")
        ## Find CMake-generated package config when consuming the (installed) conan package
        #self.cpp_info.builddirs = [os.path.join("lib", "cmake")]

        self.cpp_info.set_property("cmake_find_mode", "config")
        self.cpp_info.components["math"].set_property("cmake_target_name", "ad::math")
        self.cpp_info.components["math"].includedirs = ["include/math"]
